<!-- externally hosted scripts -->
<script type="text/javascript" src="lib/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="lib/swfobject-2.1.min.js"></script>
<!-- external libraries -->
<script type="text/javascript" src="lib/trimpath-template-1.0.38.min.js"></script>
<!-- local scripts -->
<script type="text/javascript" src="js/template.js"></script>
<script type="text/javascript" src="js/basic.js"></script>
<!-- stylesheets -->
<link rel="stylesheet" type="text/css" href="css/basic.css" />
<title>Wii Media Player</title>
