<!-- externally hosted scripts -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js"></script>
<!-- external libraries -->
<script type="text/javascript" src="lib/trimpath-template-1.0.38.min.js"></script>
<script type="text/javascript" src="lib/querystring-1.3.min.js"></script>
<script type="text/javascript" src="lib/json2.min.js"></script>
<!-- local scripts -->
<script type="text/javascript" src="js/jquery_ext.min.js"></script>
<script type="text/javascript" src="js/template.min.js"></script>
<script type="text/javascript" src="js/playlist.min.js"></script>
<script type="text/javascript" src="js/player.min.js"></script>
<script type="text/javascript" src="js/collection.min.js"></script>
<script type="text/javascript" src="js/actions.min.js"></script>
<!-- stylesheets -->
<link rel="stylesheet" type="text/css" href="css/playlist.css" />
<link rel="stylesheet" type="text/css" href="css/collection.css" />
<link rel="stylesheet" type="text/css" href="css/player.css" />

<title>&#164;&#164; Home Media Player &#164;&#164;</title>
