<!-- externally hosted scripts -->
<script type="text/javascript" src="lib/jquery-1.2.6.min.js"></script>
<script type="text/javascript" src="lib/jquery-ui-personalized-1.5.2.min.js"></script>
<script type="text/javascript" src="lib/swfobject-2.1.min.js"></script>
<!-- external libraries -->
<script type="text/javascript" src="lib/trimpath-template-1.0.38.min.js"></script>
<script type="text/javascript" src="lib/querystring-1.3.min.js"></script>
<script type="text/javascript" src="lib/json2.min.js"></script>
<!-- local scripts -->
<script type="text/javascript" src="js/jquery_ext.js"></script>
<script type="text/javascript" src="js/template.js"></script>
<script type="text/javascript" src="js/playlist.js"></script>
<script type="text/javascript" src="js/player.js"></script>
<script type="text/javascript" src="js/collection.js"></script>
<script type="text/javascript" src="js/actions.js"></script>
<!-- stylesheets -->
<link rel="stylesheet" type="text/css" href="css/playlist.css" />
<link rel="stylesheet" type="text/css" href="css/collection.css" />
<link rel="stylesheet" type="text/css" href="css/player.css" />

<title>&#164;&#164; Home Media Player &#164;&#164;</title>
