<!-- externally hosted scripts -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js"></script>
<!-- external libraries -->
<script type="text/javascript" src="lib/trimpath-template-1.0.38.min.js"></script>
<!-- local scripts -->
<script type="text/javascript" src="js/template.js"></script>
<script type="text/javascript" src="js/basic.js"></script>
<!-- stylesheets -->
<link rel="stylesheet" type="text/css" href="css/basic.css" />
<title>Wii Media Player</title>
